# Generated by Django 4.2.7 on 2023-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dataHMS",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("nama", models.CharField(blank=True, max_length=100, null=True)),
                ("tgl_lahir", models.DateField(blank=True, null=True)),
                ("alamat", models.CharField(blank=True, max_length=200, null=True)),
                ("height", models.CharField(blank=True, max_length=200, null=True)),
                ("weight", models.CharField(blank=True, max_length=200, null=True)),
                ("gender", models.CharField(blank=True, max_length=200, null=True)),
                ("tgl_masuk", models.DateField(blank=True, null=True)),
                ("diagnosis", models.CharField(blank=True, max_length=200, null=True)),
                ("bed", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={"db_table": "data_hms",},
        ),
    ]
